# Generated by Django 5.0.2 on 2025-05-31 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('complexity', models.CharField(choices=[('simple', 'Простая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=10)),
                ('features_count', models.IntegerField()),
                ('need_design', models.BooleanField(default=False)),
                ('need_integration', models.BooleanField(default=False)),
                ('has_spec', models.BooleanField(default=False)),
                ('application_type', models.CharField(choices=[('web', 'Веб-приложение'), ('mobile', 'Мобильное приложение'), ('desktop', 'Десктопное приложение')], max_length=10)),
                ('estimated_time', models.IntegerField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('in_progress', 'В работе')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='teams', to='api.project')),
            ],
        ),
    ]
