# Generated by Django 5.0.2 on 2025-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taskrequest_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='application_type',
            field=models.CharField(choices=[('web', 'Веб-приложение'), ('mobile', 'Мобильное приложение'), ('desktop', 'Десктопное приложение'), ('other', 'Другое')], max_length=10),
        ),
    ]
