version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
