version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app
      - static_data:/app/staticfiles
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
  static_data: 
