version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:4000

  backend:
    build:
      context: ./backend-nest
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///data/database.sqlite
    volumes:
      - ./database.sqlite:/app/data/database.sqlite

  db:
    image: sqlite:latest
    volumes:
      - ./database.sqlite:/data/database.sqlite
